LapidaryLoader:ImportModule("LapidaryLocale"):Register("enUS", {
    PANEL_TITLE = "Lapidary",
    PANEL_CURRENCY = "Diamonds: |cFFFFFFFF%d|r    Shards: |cFFFFFFFF%d|r",

    GROUP_PRIMARY = "Primary stats",
    GROUP_SECONDARY = "Secondary stats",
    GROUP_HYBRID = "Two-stat",
    GROUP_TANK = "Tanking",

    GEM_STRENGTH = "Strength",
    GEM_AGILITY = "Agility",
    GEM_INTELLECT = "Intellect",
    GEM_SPIRIT = "Spirit",
    GEM_STAMINA = "Stamina",
    GEM_ATTACK_POWER = "Attack power",
    GEM_SPELL_POWER = "Spell power",
    GEM_HIT = "Hit rating",
    GEM_CRIT = "Critical strike rating",
    GEM_HASTE = "Haste rating",
    GEM_EXPERTISE = "Expertise rating",
    GEM_RESILIENCE = "Resilience rating",
    GEM_ARMOR_PENETRATION = "Armor penetration rating",
    GEM_SPELL_PENETRATION = "Spell penetration",
    GEM_MP5 = "Mana per 5 sec",
    GEM_DEFENSE = "Defense rating",
    GEM_DODGE = "Dodge rating",
    GEM_PARRY = "Parry rating",
    GEM_BLOCK_RATING = "Block rating",
    GEM_BLOCK_VALUE = "Block value",
    GEM_STRENGTH_HIT = "Strength and hit",
    GEM_STRENGTH_CRIT = "Strength and crit",
    GEM_AGILITY_HIT = "Agility and hit",
    GEM_AGILITY_CRIT = "Agility and crit",
    GEM_ATTACK_POWER_HIT = "Attack power and hit",
    GEM_ATTACK_POWER_CRIT = "Attack power and crit",
    GEM_ATTACK_POWER_HASTE = "Attack power and haste",
    GEM_SPELL_POWER_HIT = "Spell power and hit",
    GEM_SPELL_POWER_CRIT = "Spell power and crit",
    GEM_SPELL_POWER_HASTE = "Spell power and haste",
    GEM_EXPERTISE_HIT = "Expertise and hit",

    ACTION_REMOVE_ALL = "Take out",
    ACTION_INSERT_ALL = "Insert",

    RESTORE_TITLE = "Return to base gem",
    RESTORE_COST = "Click a gem to turn it back into a base diamond:",
    RESTORE_ROW_HINT = "Left click - turn this gem back into a base diamond",
    RESTORE_BUTTON = "Return",
    RESTORE_IN_BAGS = "Cut gems in bags:",
    RESTORE_NOTHING = "No cut gems in bags",
    RESTORE_NO_GEM = "The vendor shows no gem to trade in",

    ACTION_REMOVE_EVERYTHING = "Take out all",
    ACTION_INSERT_EVERYTHING = "Insert all",

    TOOLTIP_REMOVE_EQUIPPED = "Take diamonds out of equipped items only",
    TOOLTIP_INSERT_EQUIPPED = "Fill free sockets on equipped items from bags: meta into meta sockets, big gems before small ones",
    TOOLTIP_REMOVE_EVERYTHING = "Take diamonds out of equipped items and out of items sitting in bags",
    TOOLTIP_INSERT_EVERYTHING = "Fill free sockets on equipped items and on items sitting in bags",

    TOOLTIP_BUY_ONE = "Left click - buy one",
    TOOLTIP_BUY_TEN = "Shift + left click - buy ten",
    TOOLTIP_BUY_ALL = "Ctrl + left click - buy as many as you can afford",

    SLASH_HELP_HEADER = "commands:",
    SLASH_HELP_OUT = "take every legendary gem out",
    SLASH_HELP_IN = "insert gems from bags into free sockets",
    SLASH_HELP_SWAP = "take out, then insert",
    SLASH_HELP_TOGGLE = "enable or disable the addon",
    SLASH_HELP_STATUS = "print current state",
    SLASH_HELP_SCOPE = "append all to out/in/swap to include items sitting in bags",
    SLASH_HELP_RESETPOS = "move the button bar back to its default spot",
    SLASH_POS_RESET = "button bar position reset.",
    SLASH_ENABLED = "enabled.",
    SLASH_DISABLED = "disabled.",

    STATUS_ENABLED = "enabled: %s",
    STATUS_AUTO_SWAP = "swap on equipment set: %s",
    STATUS_HOOK = "equipment set hook installed: %s",
    STATUS_CURRENCY = "black diamonds: %d",
    STATUS_LAST_RUN = "last run: %s gems removed, %s slots scanned",
}, true)
