local L = LibStub("AceLocale-3.0"):NewLocale("Lapidary", "enUS", true, true)
if not L then return end

L["PANEL_TITLE"] = "Black Diamonds"
L["PANEL_CURRENCY"] = "Diamonds: |cFFFFFFFF%d|r    Shards: |cFFFFFFFF%d|r"

L["GROUP_PRIMARY"] = "Primary stats"
L["GROUP_SECONDARY"] = "Secondary stats"
L["GROUP_HYBRID"] = "Two-stat"
L["GROUP_TANK"] = "Tanking"

L["GEM_STRENGTH"] = "Strength"
L["GEM_AGILITY"] = "Agility"
L["GEM_INTELLECT"] = "Intellect"
L["GEM_SPIRIT"] = "Spirit"
L["GEM_STAMINA"] = "Stamina"
L["GEM_ATTACK_POWER"] = "Attack power"
L["GEM_SPELL_POWER"] = "Spell power"
L["GEM_HIT"] = "Hit rating"
L["GEM_CRIT"] = "Critical strike rating"
L["GEM_HASTE"] = "Haste rating"
L["GEM_EXPERTISE"] = "Expertise rating"
L["GEM_RESILIENCE"] = "Resilience rating"
L["GEM_ARMOR_PENETRATION"] = "Armor penetration rating"
L["GEM_SPELL_PENETRATION"] = "Spell penetration"
L["GEM_MP5"] = "Mana per 5 sec"
L["GEM_DEFENSE"] = "Defense rating"
L["GEM_DODGE"] = "Dodge rating"
L["GEM_PARRY"] = "Parry rating"
L["GEM_BLOCK_RATING"] = "Block rating"
L["GEM_BLOCK_VALUE"] = "Block value"
L["GEM_STRENGTH_HIT"] = "Strength and hit"
L["GEM_STRENGTH_CRIT"] = "Strength and crit"
L["GEM_AGILITY_HIT"] = "Agility and hit"
L["GEM_AGILITY_CRIT"] = "Agility and crit"
L["GEM_ATTACK_POWER_HIT"] = "Attack power and hit"
L["GEM_ATTACK_POWER_CRIT"] = "Attack power and crit"
L["GEM_ATTACK_POWER_HASTE"] = "Attack power and haste"
L["GEM_SPELL_POWER_HIT"] = "Spell power and hit"
L["GEM_SPELL_POWER_CRIT"] = "Spell power and crit"
L["GEM_SPELL_POWER_HASTE"] = "Spell power and haste"
L["GEM_EXPERTISE_HIT"] = "Expertise and hit"

L["ACTION_REMOVE_ALL"] = "Take out"
L["ACTION_INSERT_ALL"] = "Insert"

L["TOOLTIP_BUY_ONE"] = "Left click - buy one"
L["TOOLTIP_BUY_TEN"] = "Shift + left click - buy ten"
L["TOOLTIP_BUY_ALL"] = "Ctrl + left click - buy as many as you can afford"

L["SLASH_HELP_HEADER"] = "commands:"
L["SLASH_HELP_OUT"] = "take every legendary gem out"
L["SLASH_HELP_IN"] = "insert gems from bags into free sockets"
L["SLASH_HELP_SWAP"] = "take out, then insert"
L["SLASH_HELP_TOGGLE"] = "enable or disable the addon"
L["SLASH_HELP_STATUS"] = "print current state"
L["SLASH_ENABLED"] = "enabled."
L["SLASH_DISABLED"] = "disabled."

L["STATUS_ENABLED"] = "enabled: %s"
L["STATUS_AUTO_SWAP"] = "swap on equipment set: %s"
L["STATUS_HOOK"] = "equipment set hook installed: %s"
L["STATUS_CURRENCY"] = "black diamonds: %d"
L["STATUS_LAST_RUN"] = "last run: %s gems removed, %s slots scanned"
