LapidaryLoader:ImportModule("LapidaryLocale"):Register("ruRU", {
    PANEL_TITLE = "Огранка",
    PANEL_CURRENCY = "Бриллианты: |cFFFFFFFF%d|r    Осколки: |cFFFFFFFF%d|r",

    GROUP_PRIMARY = "Основные статы",
    GROUP_SECONDARY = "Вторичные статы",
    GROUP_HYBRID = "Двойные",
    GROUP_TANK = "Танковские",

    GEM_STRENGTH = "Сила",
    GEM_AGILITY = "Ловкость",
    GEM_INTELLECT = "Интеллект",
    GEM_SPIRIT = "Дух",
    GEM_STAMINA = "Выносливость",
    GEM_ATTACK_POWER = "Сила атаки",
    GEM_SPELL_POWER = "Сила заклинаний",
    GEM_HIT = "Рейтинг меткости",
    GEM_CRIT = "Рейтинг критического удара",
    GEM_HASTE = "Рейтинг скорости",
    GEM_EXPERTISE = "Рейтинг мастерства",
    GEM_RESILIENCE = "Рейтинг устойчивости",
    GEM_ARMOR_PENETRATION = "Рейтинг пробивания брони",
    GEM_SPELL_PENETRATION = "Проникающая способность заклинаний",
    GEM_MP5 = "Мана в 5 секунд",
    GEM_DEFENSE = "Рейтинг защиты",
    GEM_DODGE = "Рейтинг уклонения",
    GEM_PARRY = "Рейтинг парирования",
    GEM_BLOCK_RATING = "Рейтинг блокирования щитом",
    GEM_BLOCK_VALUE = "Показатель блокирования",
    GEM_STRENGTH_HIT = "Сила и меткость",
    GEM_STRENGTH_CRIT = "Сила и крит",
    GEM_AGILITY_HIT = "Ловкость и меткость",
    GEM_AGILITY_CRIT = "Ловкость и крит",
    GEM_ATTACK_POWER_HIT = "Сила атаки и меткость",
    GEM_ATTACK_POWER_CRIT = "Сила атаки и крит",
    GEM_ATTACK_POWER_HASTE = "Сила атаки и скорость",
    GEM_SPELL_POWER_HIT = "Сила заклинаний и меткость",
    GEM_SPELL_POWER_CRIT = "Сила заклинаний и крит",
    GEM_SPELL_POWER_HASTE = "Сила заклинаний и скорость",
    GEM_EXPERTISE_HIT = "Мастерство и меткость",

    ACTION_REMOVE_ALL = "Достать",
    ACTION_INSERT_ALL = "Вставить",

    RESTORE_TITLE = "Вернуть в исходный",
    RESTORE_COST = "Нажми на камень, чтобы вернуть его в исходный:",
    RESTORE_ROW_HINT = "ЛКМ — вернуть этот камень в исходный",
    RESTORE_BUTTON = "Вернуть",
    RESTORE_IN_BAGS = "Огранённые камни в сумках:",
    RESTORE_NOTHING = "Огранённых камней в сумках нет",
    RESTORE_NO_GEM = "Торговец не показывает камень к обмену",

    ACTION_REMOVE_EVERYTHING = "Достать все",
    ACTION_INSERT_EVERYTHING = "Вставить все",

    TOOLTIP_REMOVE_EQUIPPED = "Вынуть бриллианты только из надетых вещей",
    TOOLTIP_INSERT_EQUIPPED = "Разложить бриллианты из сумок по свободным гнёздам надетых вещей: мета в мета-гнёзда, крупные вперёд мелких",
    TOOLTIP_REMOVE_EVERYTHING = "Вынуть бриллианты и из надетых вещей, и из вещей, лежащих в сумках",
    TOOLTIP_INSERT_EVERYTHING = "Заполнить свободные гнёзда и на надетых вещах, и на вещах в сумках",

    TOOLTIP_BUY_ONE = "ЛКМ — купить один",
    TOOLTIP_BUY_TEN = "Shift + ЛКМ — купить десять",
    TOOLTIP_BUY_ALL = "Ctrl + ЛКМ — купить столько, на сколько хватит",

    SLASH_HELP_HEADER = "команды:",
    SLASH_HELP_OUT = "вынуть все легендарные камни",
    SLASH_HELP_IN = "вставить камни из сумок в свободные гнёзда",
    SLASH_HELP_SWAP = "вынуть, затем вставить",
    SLASH_HELP_TOGGLE = "включить или выключить аддон",
    SLASH_HELP_STATUS = "показать текущее состояние",
    SLASH_HELP_SCOPE = "добавь all к out/in/swap, чтобы захватить и вещи в сумках",
    SLASH_HELP_RESETPOS = "вернуть панель кнопок на место",
    SLASH_POS_RESET = "позиция панели сброшена.",
    SLASH_ENABLED = "включён.",
    SLASH_DISABLED = "выключен.",

    STATUS_ENABLED = "включён: %s",
    STATUS_AUTO_SWAP = "перенос при смене сета: %s",
    STATUS_HOOK = "хук на менеджер сетов установлен: %s",
    STATUS_CURRENCY = "чёрных бриллиантов: %d",
    STATUS_LAST_RUN = "последний прогон: вынуто %s, просмотрено слотов %s",
})
