LapidaryLoader:ImportModule("LapidaryLocale"):Register("ruRU", {
    PANEL_TITLE = "Огранка",
    PANEL_CURRENCY = "Бриллианты: |cFFFFFFFF%d|r    Осколки: |cFFFFFFFF%d|r",

    GROUP_PRIMARY = "Основные статы",
    GROUP_SECONDARY = "Вторичные статы",
    GROUP_HYBRID = "Двойные",
    GROUP_TANK = "Танковские",

    GEM_STRENGTH = "Сила",
    GEM_AGILITY = "Ловкость",
    GEM_INTELLECT = "Интеллект",
    GEM_SPIRIT = "Дух",
    GEM_STAMINA = "Выносливость",
    GEM_ATTACK_POWER = "Сила атаки",
    GEM_SPELL_POWER = "Сила заклинаний",
    GEM_HIT = "Рейтинг меткости",
    GEM_CRIT = "Рейтинг критического удара",
    GEM_HASTE = "Рейтинг скорости",
    GEM_EXPERTISE = "Рейтинг мастерства",
    GEM_RESILIENCE = "Рейтинг устойчивости",
    GEM_ARMOR_PENETRATION = "Рейтинг пробивания брони",
    GEM_SPELL_PENETRATION = "Проникающая способность заклинаний",
    GEM_MP5 = "Мана в 5 секунд",
    GEM_DEFENSE = "Рейтинг защиты",
    GEM_DODGE = "Рейтинг уклонения",
    GEM_PARRY = "Рейтинг парирования",
    GEM_BLOCK_RATING = "Рейтинг блокирования щитом",
    GEM_BLOCK_VALUE = "Показатель блокирования",
    GEM_STRENGTH_HIT = "Сила и меткость",
    GEM_STRENGTH_CRIT = "Сила и крит",
    GEM_AGILITY_HIT = "Ловкость и меткость",
    GEM_AGILITY_CRIT = "Ловкость и крит",
    GEM_ATTACK_POWER_HIT = "Сила атаки и меткость",
    GEM_ATTACK_POWER_CRIT = "Сила атаки и крит",
    GEM_ATTACK_POWER_HASTE = "Сила атаки и скорость",
    GEM_SPELL_POWER_HIT = "Сила заклинаний и меткость",
    GEM_SPELL_POWER_CRIT = "Сила заклинаний и крит",
    GEM_SPELL_POWER_HASTE = "Сила заклинаний и скорость",
    GEM_EXPERTISE_HIT = "Мастерство и меткость",

    ACTION_REMOVE_ALL = "Достать",
    ACTION_INSERT_ALL = "Вставить",

    TOOLTIP_BUY_ONE = "ЛКМ — купить один",
    TOOLTIP_BUY_TEN = "Shift + ЛКМ — купить десять",
    TOOLTIP_BUY_ALL = "Ctrl + ЛКМ — купить столько, на сколько хватит",

    SLASH_HELP_HEADER = "команды:",
    SLASH_HELP_OUT = "вынуть все легендарные камни",
    SLASH_HELP_IN = "вставить камни из сумок в свободные гнёзда",
    SLASH_HELP_SWAP = "вынуть, затем вставить",
    SLASH_HELP_TOGGLE = "включить или выключить аддон",
    SLASH_HELP_STATUS = "показать текущее состояние",
    SLASH_ENABLED = "включён.",
    SLASH_DISABLED = "выключен.",

    STATUS_ENABLED = "включён: %s",
    STATUS_AUTO_SWAP = "перенос при смене сета: %s",
    STATUS_HOOK = "хук на менеджер сетов установлен: %s",
    STATUS_CURRENCY = "чёрных бриллиантов: %d",
    STATUS_LAST_RUN = "последний прогон: вынуто %s, просмотрено слотов %s",
})
