local L = LibStub("AceLocale-3.0"):NewLocale("BlackDiamonds", "ruRU")
if not L then return end

L["PANEL_TITLE"] = "Чёрные бриллианты"
L["PANEL_CURRENCY"] = "Бриллианты: |cFFFFFFFF%d|r    Осколки: |cFFFFFFFF%d|r"

L["GROUP_PRIMARY"] = "Основные статы"
L["GROUP_SECONDARY"] = "Вторичные статы"
L["GROUP_HYBRID"] = "Двойные"
L["GROUP_TANK"] = "Танковские"

L["GEM_STRENGTH"] = "Сила"
L["GEM_AGILITY"] = "Ловкость"
L["GEM_INTELLECT"] = "Интеллект"
L["GEM_SPIRIT"] = "Дух"
L["GEM_STAMINA"] = "Выносливость"
L["GEM_ATTACK_POWER"] = "Сила атаки"
L["GEM_SPELL_POWER"] = "Сила заклинаний"
L["GEM_HIT"] = "Рейтинг меткости"
L["GEM_CRIT"] = "Рейтинг критического удара"
L["GEM_HASTE"] = "Рейтинг скорости"
L["GEM_EXPERTISE"] = "Рейтинг мастерства"
L["GEM_RESILIENCE"] = "Рейтинг устойчивости"
L["GEM_ARMOR_PENETRATION"] = "Рейтинг пробивания брони"
L["GEM_SPELL_PENETRATION"] = "Проникающая способность заклинаний"
L["GEM_MP5"] = "Мана в 5 секунд"
L["GEM_DEFENSE"] = "Рейтинг защиты"
L["GEM_DODGE"] = "Рейтинг уклонения"
L["GEM_PARRY"] = "Рейтинг парирования"
L["GEM_BLOCK_RATING"] = "Рейтинг блокирования щитом"
L["GEM_BLOCK_VALUE"] = "Показатель блокирования"
L["GEM_STRENGTH_HIT"] = "Сила и меткость"
L["GEM_STRENGTH_CRIT"] = "Сила и крит"
L["GEM_AGILITY_HIT"] = "Ловкость и меткость"
L["GEM_AGILITY_CRIT"] = "Ловкость и крит"
L["GEM_ATTACK_POWER_HIT"] = "Сила атаки и меткость"
L["GEM_ATTACK_POWER_CRIT"] = "Сила атаки и крит"
L["GEM_ATTACK_POWER_HASTE"] = "Сила атаки и скорость"
L["GEM_SPELL_POWER_HIT"] = "Сила заклинаний и меткость"
L["GEM_SPELL_POWER_CRIT"] = "Сила заклинаний и крит"
L["GEM_SPELL_POWER_HASTE"] = "Сила заклинаний и скорость"
L["GEM_EXPERTISE_HIT"] = "Мастерство и меткость"

L["ACTION_REMOVE_ALL"] = "Достать"
L["ACTION_INSERT_ALL"] = "Вставить"

L["TOOLTIP_BUY_ONE"] = "ЛКМ — купить один"
L["TOOLTIP_BUY_TEN"] = "Shift + ЛКМ — купить десять"
L["TOOLTIP_BUY_ALL"] = "Ctrl + ЛКМ — купить столько, на сколько хватит"

L["SLASH_HELP_HEADER"] = "команды:"
L["SLASH_HELP_OUT"] = "вынуть все легендарные камни"
L["SLASH_HELP_IN"] = "вставить камни из сумок в свободные гнёзда"
L["SLASH_HELP_SWAP"] = "вынуть, затем вставить"
L["SLASH_HELP_TOGGLE"] = "включить или выключить аддон"
L["SLASH_HELP_STATUS"] = "показать текущее состояние"
L["SLASH_ENABLED"] = "включён."
L["SLASH_DISABLED"] = "выключен."

L["STATUS_ENABLED"] = "включён: %s"
L["STATUS_AUTO_SWAP"] = "перенос при смене сета: %s"
L["STATUS_HOOK"] = "хук на менеджер сетов установлен: %s"
L["STATUS_CURRENCY"] = "чёрных бриллиантов: %d"
L["STATUS_LAST_RUN"] = "последний прогон: вынуто %s, просмотрено слотов %s"
